services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: studyapp
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: study_quiz
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c log_statement=all
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U studyapp -d study_quiz"]
      interval: 5s
      timeout: 10s
      retries: 5

  app:
    build: .
    command: >
      sh -c "
        until pg_isready -h postgres -p 5432 -U studyapp; do
          echo 'Waiting for PostgreSQL to be ready...';
          sleep 2;
        done;
        streamlit run app.py --server.port=8501 --server.address=0.0.0.0
      "
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - DATABASE_URL=postgresql://studyapp:password123@postgres:5432/study_quiz
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
