version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: studyapp
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: study_quiz
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c log_statement=all

volumes:
  postgres_data:
