[project]
# Pythonアプリとして認識
runtime = "python"

[setup]
commands = [
  "python -m pip install --upgrade pip"
]

[install]
commands = [
  "pip install --no-cache-dir -r requirements.txt"
]

[build]
commands = []

[[services]]
command = "streamlit run app.py --server.port ${PORT} --server.address 0.0.0.0"
ports = ["${PORT}"]
