[server]
# Railway対応設定
headless = true
enableCORS = true
enableXsrfProtection = false
port = 8080
address = "0.0.0.0"
runOnSave = false
allowRunOnSave = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
# テーマ設定
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
