[server]
# ローカル開発用設定
headless = false
enableCORS = false
enableXsrfProtection = false
port = 8501
address = "localhost"
runOnSave = true
allowRunOnSave = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
# テーマ設定
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
